name: Pull Request Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4.1.0

      - name: Build with Gradle
        run: ./gradlew detekt lintRelease assembleRelease testRelease
